services:
  atcoder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: atcoder
    container_name: atcoder-container
    tty: true
    volumes:
      - ../../atcoder:/contest/atcoder
      - ../../ac-library:/contest/ac-library
      - ../../my-library:/contest/my-library
      - ./.bashrc:/root/.bashrc
    ulimits:
      stack: -1  # スタックサイズを無制限に設定
